### ISSUE TITLE
Reg: Discuss format of UUID

### ISSUE THREAD

**Issue by fetmar** [ICTatRTI/coconut#42]
The system will generate a unique code automatically. The M&E have talked about this type of code. Are we keeping this format, right?: 

Albert Einstein + 14 04 1879 = AE14041879

**Comment by fetmar** [comment]
Right now it's a random UUID based on Crockford's Base 32 with a check digit. It looks like 348-Y0F-AF0
8 digits makes 1,099,511,627,776 possibilities putting the likelyhood of a collision extremely low.

Juan Lopez and Jose Lopez both born on the same day however will have the same UUID if we use the scheme mentioned above.

**Comment by carl-fisher** [comment]
From an email thread with Wayne:

The unique ID we have discussed is based on the first letter of the paternal last name, the first letter of the first name, the year of birth, gender code, and a Barrio code (based on table codes). Thus, the Unique ID for Juan Salazar Ramos born on August 10, 1999 who is male (Male = 1, Female=2) from Barrio (assuming Boca Chica=33) would be SJ10081999133. Notice YOB is ddmmyy.

[carlf] The trouble is it would not be hard to have different people with the same ID using that plan.  Twin boys (Juan and Jose) or even cousins who happened to have the same birthday would have the same “unique” ID.  Also, I thought we were not planning on using birth date, since some youth may not know them, or at least not exactly.  If someone only knew their birth year, what would be entered for day and month?

There will be exceedingly few people who do not know their date of birth – probably less than one in a thousand.  We have to draw the line somewhere. Create an alternative code for people who don’t know their DOB. Use the intake date with 9999 as the year.
For true duplicates – we could add a sequence number to the end of the Unique ID so, the second SJ10081999133 that occurs would be SJ10081999133-2. This could require an supervisor override function for more integrity.

**Comment by vbakalov** [comment]
The UUID is generated as described above by Josh and it works fine.
